/** @format */
import {
  FontLoader,
  OrbitControls,
  TextGeometry,
} from "three/examples/jsm/Addons.js";
import "./style.css";
import * as THREE from "three";
import GUI from "lil-gui";

let generatorWorker: Worker | null = null;
let cloudMesh = new THREE.Mesh();

//canvas set up
const CANVAS: HTMLCanvasElement | null = document.querySelector("#three");

if (!CANVAS) throw new Error("Canvas is undefined!");

let WIDTH = CANVAS.clientWidth;
let HEIGHT = CANVAS.clientHeight;

//set up debug ui
const gui = new GUI();

//scene set up
const scene = new THREE.Scene();
scene.add(cloudMesh);

//create texture loader
const textureLoader = new THREE.TextureLoader();
const matcap1 = textureLoader.load("/textures/matcaps/8.png");

// material
const material = new THREE.MeshMatcapMaterial({});
gui.add(material, "wireframe");
matcap1.colorSpace = THREE.SRGBColorSpace;
material.matcap = matcap1;

//add axes helper
const axesHelper = new THREE.AxesHelper();
scene.add(axesHelper);
axesHelper.visible = false;

gui.add(axesHelper, "visible").name("Show axeses");

//import font and generate text geom
const fontLoader = new FontLoader();
fontLoader.load("/fonts/Mulish_Regular.json", (font) => {
  const geom = new TextGeometry("Swedka121", {
    font,
    size: 0.5,
    curveSegments: 5,
    depth: 0.2,
    bevelEnabled: true,
    bevelSize: 0.02,
    bevelSegments: 2,
    bevelThickness: 0.03,
  });

  // geom.computeBoundingBox();
  // console.log(geom.boundingBox);
  // geom.translate(
  //   -((geom.boundingBox?.max.x || 0) - 0.02) * 0.5,
  //   -((geom.boundingBox?.max.y || 0) - 0.02) * 0.5,
  //   -((geom.boundingBox?.max.z || 0) - 0.03) * 0.5
  // );
  geom.center();
  const textMesh = new THREE.Mesh(geom, material);
  scene.add(textMesh);
});

function generateCloud(COF1 = 100, COF2 = 20) {
  if (generatorWorker) generatorWorker.terminate(); // remove old worker
  generatorWorker = new Worker(new URL("./worker.ts", import.meta.url), {
    // creating new worker
    type: "module",
  });
  generatorWorker.postMessage(["generate", COF1, COF2]);
  generatorWorker.addEventListener("message", (ev) => {
    if (ev.data[0] == "generated") {
      const geom = new THREE.BufferGeometry();
      for (const [a, a1] of Object.entries(ev.data[1])) {
        // set attributes from like-attribute class object
        geom.setAttribute(
          a,
          new THREE.BufferAttribute(
            (a1 as { array: Float32Array }).array,
            (a1 as { itemSize: number }).itemSize
          )
        );
      }
      scene.remove(cloudMesh);
      cloudMesh = new THREE.Mesh(geom, material);
      scene.add(cloudMesh);
    }
  });
}

generateCloud(); // just make sure that cloud is generated by default
let numberOfObjects = { number: 100, number2: 20 };
gui
  .add(numberOfObjects, "number")
  .name("Count of objects")
  .onChange(async (v: number) => {
    generateCloud(numberOfObjects.number2, v);
  })
  .min(1)
  .max(10000)
  .step(1);
gui
  .add(numberOfObjects, "number2")
  .name("Size of generated cloud")
  .onChange(async (v: number) => {
    generateCloud(v, numberOfObjects.number);
  })
  .min(1)
  .max(1000)
  .step(1);

//camera set up
const camera = new THREE.PerspectiveCamera(75, WIDTH / HEIGHT, 0.01, 1000);
const orbitControls = new OrbitControls(camera, CANVAS);
camera.position.set(2, 2, 2);
camera.lookAt(0, 0, 0);

//renderer
const renderer = new THREE.WebGLRenderer({
  canvas: CANVAS,
});

renderer.setSize(WIDTH, HEIGHT);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));

function render() {
  orbitControls.update();
  renderer.clear();

  renderer.render(scene, camera);

  requestAnimationFrame(render);
}

render();

window.addEventListener("resize", () => {
  WIDTH = window.innerWidth;
  HEIGHT = window.innerHeight;
  renderer.setSize(WIDTH, HEIGHT);
  camera.aspect = WIDTH / HEIGHT;
  camera.updateProjectionMatrix();
});
